[package]
name = "expr"
version = "0.1.0"
authors = ["mats@kindahl.net"]

[dependencies]
env_logger = "~0.5"
log = "~0.4"
assert_matches = "~1.4"

[dev-dependencies]
criterion = "~0.3"

[[bench]]
name = "simple"
harness = false