name: Rust checks
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Crate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  clippy:
    name: Run Clippy on Crate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clippy
      run: cargo clippy --verbose
  docker:
    name: Build and check Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          load: true
          tags: expr-rs:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Run executable
        run: docker run expr-rs:latest '2+2'
